services:
  wg-easy:
    container_name: wg-easy
    image: weejewel/wg-easy
    restart: unless-stopped
    env_file:
      - wg-easy.env
    volumes:
      - ./data:/etc/wireguard
    ports:
      - "${WG_PORT:-51820}:${WG_PORT:-51820}/udp"
      - "${PORT:-51821}:${PORT:-51821}/tcp"
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
